<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  </head>

  <body>
    <a href="/01. async-await-intro.html">01. async-await-intro</a>
    <a href="/02. axios-and-async.html">02. axios-and-async</a>
    <a href="/03. catchError.html">03. catchError</a>


    <h1>使用 Async 與基本介紹</h1>
    <h3>async function : <a href="https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/async_function">https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/async_function</a></h3>
    <h3>await : <a href="https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Operators/await">https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Operators/await</a></h3>
    <h3>try...catch 語法 : <a href="https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/try...catch">https://developer.mozilla.org/zh-TW/docs/Web/JavaScript/Reference/Statements/try...catch</a></h3>


    <div>Async 傳統函式，加入 await 逐行執行 ( 未加上 await, 只顯示 Promise 函式 )</div>
    <div>Async Function 錯誤捕捉， try , catch</div>

  </body>
</html>

<script>
  // 建立具有 Promise 的函式（可帶參數）
  function promiseFn(num) {
    // 這裡可以插入其它程式碼
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (num) {
          resolve('成功');
        } else {
          // reject(new Error('失敗'));
          reject('失敗');
        }
      }, 0);
    });
  }

  // Promise 寫法
  function sample_promise(){
    promiseFn(1)
      .then((res) => {
        console.log("res:", res);
        return promiseFn(0);  // 透過 return 進行串接
      })
      .then((res) => {
        console.log(2, res);
      })
      .catch((err)=> {
        // 1.
        console.log(err);
        // 2.
        // alert(err);
      })
  }


  // Async 傳統函式, 加入 await 逐行執行
  function sample_async(){
    async function asyncFn() {
      console.log(1);
      const res1 = await promiseFn(1); // Promise
      console.log(2, res1);
      const res2 = await promiseFn(0);
      console.log(3, res2);
    }
    asyncFn();
  
  
    // Async 箭頭函式
    const asyncArrowFn = async () => {
      
    }
  }


  // Async Function 錯誤捕捉
  function sample_tryCatch(){
    (async () => {
      try {
        const res1 = await promiseFn(1);
        console.log("res1:", res1);
        const res2 = await promiseFn(0);
        console.log("res2:", res2);
      }
      catch (error) {
        console.log("error:", error);
        // alert(error);
      }
    })(); // IIFE 立即函式
  }

  
  function sample_tryCatch2(){
    // 1. 傳統函式
    // async function asyncFn(num) {
    //   try {
    //     const res = await promiseFn(num);
    //     return res;
    //   } catch (error) {
    //     throw new Error('Fail');
    //   }
    // }
  
    // 2. 箭頭函式
    const asyncFn = async (num) => {
      try {
        const res = await promiseFn(num);
        // console.log("res:", res);
        return res;
      }
      catch (error) {
        throw new Error('失敗');  // throw 拋出錯誤訊息
      }
    };
  
    // 2.1
    console.log("asyncFn:", asyncFn);
    console.log("asyncFn():", asyncFn(1));  // Promise 形式運行
  
    // 2.2
    // asyncFn(1)
    //   .then((res1) => {
    //     console.log("res1:", res1);
    //     return asyncFn(0);
    //   })
    //   .then((res2) => {
    //     console.log("res2:", res2);
    //   })
    //   .catch((err) => {
    //     console.log("err:", err);
    //   });
  }



  function resolveAfter2Seconds(x) {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(x);
      }, 2000);
    });
  }

  async function add1(x) {
    const a = await resolveAfter2Seconds(20);
    const b = await resolveAfter2Seconds(30);

    // console.log(a, b);
    return x + a + b; // 第一個 await 而暫停了兩秒，接著為了第二個 await 又暫停了兩秒
  }

  add1(10).then(v => {
    console.log("add1:", v);  // prints 60 after 4 seconds.
  });

  async function add2(x) {
    const c = resolveAfter2Seconds(20);
    const d = resolveAfter2Seconds(30);
    
    // console.log(c , d);
    return x + await c + await d; // 兩個計時器都被建立起來、也都執行 await 過了. await 呼叫都在連續運行，而非平行運行
  }

  add2(20).then(v => {
    console.log("add2:", v);  // prints 60 after 2 seconds.
  });

</script>